version: "3.8"
services:
  api-gateway:
    container_name: api-gateway
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - rmqnet
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      default:
        aliases:
          - rmqnet

networks:
  default:
    name: rmqnet